### ISSUE TITLE
[FEATURE] Deprecate `no-std-net`

### ISSUE THREAD

**Issue by Sicheng-Pan** [vpetrigo/sntpc#30]
**Is your feature request related to a problem? Please describe.**
- I'm trying to use the crate without `std`. I'm unable to implement `NtpUdpSocket` trait since I have no access to `std::net::ToSocketAddrs` trait. It should be possible to use `no-std-net` as a workaround (I have not tried this yet), but it seems the upstream RFC has been addressed a while ago.
https://github.com/vpetrigo/sntpc/blob/6f2a11aef29ab3e06e239e4496bea5fe9e7ec8fa/Cargo.toml#L32-L33

**Describe the solution you'd like**
- Is it possible to avoid the usage of `std`, as the RFC has been addressed?

**Describe alternatives you've considered**
- Continue to use `no-std-net`

**Additional context**
- I'm trying to run this on a Rawsberry Pi Pico WH with [Embassy](https://embassy.dev/).

**Comment by vpetrigo** [comment]
Hello @Sicheng-Pan,
`no-std-net` already presented when you do not use `std` feature. There is an example with [`smoltcp` stack](https://github.com/vpetrigo/sntpc/blob/master/examples/smoltcp_request.rs) that should provide you an overview how to implement `NtpUdpSocket`. Since `no-std-net` is already here, you should be able to use `no_std::ToSocketAddrs` instead of `std` implementation.

I will check RFC at some point. If you want to elaborate on that and prepare a PR, it will be greatly appreciated. 😄

**Comment by Sicheng-Pan** [comment]
> Hello @Sicheng-Pan, `no-std-net` already presented when you do not use `std` feature. There is an example with [`smoltcp` stack](https://github.com/vpetrigo/sntpc/blob/master/examples/smoltcp_request.rs) that should provide you an overview how to implement `NtpUdpSocket`. Since `no-std-net` is already here, you should be able to use `no_std::ToSocketAddrs` instead of `std` implementation.

Thanks for the quick reply. It seems the `no-std-net` dependency is not present for me if I disable the default features (`sntpc = { version = "*", default-features = false }
` in my  `Cargo.toml`). I assume the example is reusing the `Cargo.toml` at the crate root, which has the `no-std-net` specified.

**Comment by vpetrigo** [comment]
@Sicheng-Pan `no-std-net` types should be properly re-exported by the crate. I will think about deprecation of the `no-std-net` in a meantime. Now I do not want to do so, because it implements `ToSockAddrs` for its types, which is not available in the `core`.

Feel free to reopen the issue if it does not fit your expectations. 😁
